### ISSUE TITLE
Texture problem

### ISSUE THREAD

**Issue by fe4rplayz** [space928/Blender-O3D-IO-Public#79] opened 2023-09-02 17:20 UTC
As I successfully import the o3d model to OMSI, the texture is not accurate.

### Expected behaviour
The texture should be shown correctly.

### Screenshots
![image](https://github.com/space928/Blender-O3D-IO-Public/assets/143898993/6d828572-7801-4b02-87a3-9d5ac689acac)

**Comment by space928** [comment] 2023-09-10 20:32
Duplicate of #59

**Closed as not planned by space928** 2023-09-10 20:32 UTC
Labels: bug, duplicate
