### ISSUE TITLE
After exporting, the texture will slide

### ISSUE THREAD

**Issue by BuliTomi22** [space928/Blender-O3D-IO-Public#90] opened 2024-01-05 15:15 UTC
### The Problem
After I export my object and open the omsi editor, the texture of the object completely slips.

0. I arrange the texture in a blender
1. I export the object in SCO
2. I put the SCO file in one of the Sceneryobejcts folders, then put the image in the texture folder, and the O3D file in the model folder.
3. I open the omsi editor and put down the object
4. The shape of the object is good, but the texture slips

![image](https://github.com/space928/Blender-O3D-IO-Public/assets/155665510/9b8ed592-d6cd-4d3e-9550-2641ffc91a2d)

**Comment by space928** [comment] 2024-01-15 20:21
Duplicate of #59

**Closed as not planned by space928** 2024-01-15 20:21 UTC
Labels: bug, needs triage
