### ISSUE TITLE
Textures not showing - Blender 2.79b

### ISSUE THREAD

**Issue by ShowTNTC** [space928/Blender-O3D-IO-Public#44] opened 2023-04-13 17:46 UTC
### Describe the bug
When import a cfg file on Blender 2.79b, any textures is showing on the UV Map window, in "Textured solid" and in Texture shading, but in Material and Texture windows there is textures

### To Reproduce
Steps to reproduce the behaviour:
1. Import a .cfg file
2. Put the shading on texture, or in textured solid + open the UV Map window

### Expected behaviour
See the texture on the UV Map window, and the textures with the textured solid, and the texture shading.

### Screenshots

![2023-04-13 19_44_27-Blender](https://user-images.githubusercontent.com/46968067/231841906-c853553d-b463-4bea-bae3-07b563e288ca.png)
![2023-04-13 19_44_49-Blender](https://user-images.githubusercontent.com/46968067/231841917-98356323-a4af-44ac-a972-8eb4f2194380.png)
![2023-04-13 19_45_25-Blender](https://user-images.githubusercontent.com/46968067/231841922-a2f7f76e-6f04-411e-87de-482897baf2e3.png)
![2023-04-13 19_45_34-Blender](https://user-images.githubusercontent.com/46968067/231841926-88272d18-2deb-4ac4-a088-7429dddcea1f.png)

**Comment by space928** [comment] 2023-04-17 17:23
I'm not sure I fully understand your issue, so correct me if I'm misunderstanding. In the "solid" view, you shouldn't expect to see any textures, this is normal Blender behaviour and not a bug. In the "textured" view you should see textures, but this only works if there is a light in the scene to illuminate the object (otherwise it will appear black). There is a bug with how interior lights are imported (they import in the wrong colour, but this is fixed in the next release) but I don't think that's causing a problem here. In the "material" and "rendered" views, Blender renders lights and environment lighting correctly. I would recommend avoiding using the "textured" view as the "material" view generally works better.

On another note, textures will not render in 2.79 when using Cycles, if you want to use Cycles upgrade to Blender >= 2.80. This is done to maintain compatibility with Blender Render and will not be fixed. In general I recommend upgrading to Blender 3.4 as it's the primary version this plugin supports.

**Closed by space928** 2023-04-17 17:23 UTC
Labels: bug
